/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as CartelaRouteImport } from './routes/cartela'
import { Route as MeusNumerosRouteImport } from './routes/meus-numeros'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as ResultadoRouteImport } from './routes/resultado'
import { Route as SaldoRouteImport } from './routes/saldo'
import { Route as ComprovanteProtocoloRouteImport } from './routes/comprovante.$protocolo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const CartelaRoute = CartelaRouteImport.update({
  id: '/cartela',
  path: '/cartela',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusNumerosRoute = MeusNumerosRouteImport.update({
  id: '/meus-numeros',
  path: '/meus-numeros',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoRoute = ResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const SaldoRoute = SaldoRouteImport.update({
  id: '/saldo',
  path: '/saldo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprovanteProtocoloRoute = ComprovanteProtocoloRouteImport.update({
  id: '/comprovante/$protocolo',
  path: '/comprovante/$protocolo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/cartela': typeof CartelaRoute
  '/meus-numeros': typeof MeusNumerosRoute
  '/painel': typeof PainelRoute
  '/resultado': typeof ResultadoRoute
  '/saldo': typeof SaldoRoute
  '/comprovante/$protocolo': typeof ComprovanteProtocoloRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/cartela': typeof CartelaRoute
  '/meus-numeros': typeof MeusNumerosRoute
  '/painel': typeof PainelRoute
  '/resultado': typeof ResultadoRoute
  '/saldo': typeof SaldoRoute
  '/comprovante/$protocolo': typeof ComprovanteProtocoloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/cartela': typeof CartelaRoute
  '/meus-numeros': typeof MeusNumerosRoute
  '/painel': typeof PainelRoute
  '/resultado': typeof ResultadoRoute
  '/saldo': typeof SaldoRoute
  '/comprovante/$protocolo': typeof ComprovanteProtocoloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/cartela'
    | '/meus-numeros'
    | '/painel'
    | '/resultado'
    | '/saldo'
    | '/comprovante/$protocolo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/cartela'
    | '/meus-numeros'
    | '/painel'
    | '/resultado'
    | '/saldo'
    | '/comprovante/$protocolo'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/cartela'
    | '/meus-numeros'
    | '/painel'
    | '/resultado'
    | '/saldo'
    | '/comprovante/$protocolo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  CartelaRoute: typeof CartelaRoute
  MeusNumerosRoute: typeof MeusNumerosRoute
  PainelRoute: typeof PainelRoute
  ResultadoRoute: typeof ResultadoRoute
  SaldoRoute: typeof SaldoRoute
  ComprovanteProtocoloRoute: typeof ComprovanteProtocoloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartela': {
      id: '/cartela'
      path: '/cartela'
      fullPath: '/cartela'
      preLoaderRoute: typeof CartelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-numeros': {
      id: '/meus-numeros'
      path: '/meus-numeros'
      fullPath: '/meus-numeros'
      preLoaderRoute: typeof MeusNumerosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado': {
      id: '/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof ResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saldo': {
      id: '/saldo'
      path: '/saldo'
      fullPath: '/saldo'
      preLoaderRoute: typeof SaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprovante/$protocolo': {
      id: '/comprovante/$protocolo'
      path: '/comprovante/$protocolo'
      fullPath: '/comprovante/$protocolo'
      preLoaderRoute: typeof ComprovanteProtocoloRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  CartelaRoute: CartelaRoute,
  MeusNumerosRoute: MeusNumerosRoute,
  PainelRoute: PainelRoute,
  ResultadoRoute: ResultadoRoute,
  SaldoRoute: SaldoRoute,
  ComprovanteProtocoloRoute: ComprovanteProtocoloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
